// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgHRMcfeCi8AoCMxQIZgH1Z5OTLRSuFfs',
    appId: '1:498735495742:web:1d4449eb39d1daa99e6f6f',
    messagingSenderId: '498735495742',
    projectId: 'flash-chat-a2fa3',
    authDomain: 'flash-chat-a2fa3.firebaseapp.com',
    storageBucket: 'flash-chat-a2fa3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgPpEDCWXtvMBzWpz4cOLaqnPsVP4HkM',
    appId: '1:498735495742:android:d7e41c867a22e4159e6f6f',
    messagingSenderId: '498735495742',
    projectId: 'flash-chat-a2fa3',
    storageBucket: 'flash-chat-a2fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2beQudi0DH_orz_3wOJlOqJx8fnSyhCs',
    appId: '1:498735495742:ios:3d292fbfc552501a9e6f6f',
    messagingSenderId: '498735495742',
    projectId: 'flash-chat-a2fa3',
    storageBucket: 'flash-chat-a2fa3.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2beQudi0DH_orz_3wOJlOqJx8fnSyhCs',
    appId: '1:498735495742:ios:3d292fbfc552501a9e6f6f',
    messagingSenderId: '498735495742',
    projectId: 'flash-chat-a2fa3',
    storageBucket: 'flash-chat-a2fa3.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgHRMcfeCi8AoCMxQIZgH1Z5OTLRSuFfs',
    appId: '1:498735495742:web:2bcfa20fb9828f8f9e6f6f',
    messagingSenderId: '498735495742',
    projectId: 'flash-chat-a2fa3',
    authDomain: 'flash-chat-a2fa3.firebaseapp.com',
    storageBucket: 'flash-chat-a2fa3.firebasestorage.app',
  );
}
